language: rust
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -f install -y libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
rust:
  - stable
  - beta
  - nightly
cache: cargo
